[build-system]
build-backend = "uv_build"
requires = ["uv-build>=0.11.14,<0.12"]

[project]
name = "toucan-plot"
version = "0.5.2"
requires-python = ">=3.13"
description = "A versatile PySide6 and Matplotlib-based plotting tool for CSV and SMV data files."
license = "MIT"
readme = { file = "README.md", content-type = "text/markdown" }
dependencies = [
    "pyside6>=6.0",
    "matplotlib>=3.0",
    "numpy>=1.20",
    "pyqtdarktheme>=2.1.0",
    "scienceplots>=2.2.1",
    "python-can>=4.0",
    "cantools>=39.0",
    "asammdf>=7.0",
    "pyarrow>=23.0.1",
    "chardet>=7.4.3",
]

[project.scripts]
toucan-plot = "toucan_plot.main:main"

[tool.setuptools.package-data]
toucan_plot = ["assets/**/*.svg", "assets/**/*.ico"]

[dependency-groups]
dev = [
    "nuitka[all]>=4.1",
    "uv-build>=0.11.14",
    "zstandard>=0.25.0",
]
lint = [
    "ruff>=0.15.9",
]
