# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: "TouCAN-Plot Nuitka Test Release"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.13"]
        nsis-version: ["3.11"]

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 5

    - name: "Print Debug info"
      run: |
        echo $env:USERPROFILE
        echo $env:PATH
        echo "$PWD"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install NSIS
      uses: repolevedavaj/install-nsis@v1.2.0
      with:
        nsis-version: ${{ matrix.nsis-version }}

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        python -m pip install uv
        uv venv .venv --python ${{ matrix.python-version }}
        .\.venv\Scripts\activate
        uv sync

    - name: Retrieve version
      id: version
      run: |
        echo "VERSION=1.0.0" >> $env:GITHUB_OUTPUT

    - name: Build
      run: |
        .\.venv\Scripts\activate
        uv build

    - name: Build with Nuitka (Portable)
      run: |
        .\.venv\Scripts\activate
        uv --no-progress run -- nuitka --mode=onefile --include-package=chardet --include-package=scienceplots --follow-imports --include-package-data=chardet --include-package-data=scienceplots --include-data-dir=src/toucan_plot/assets=assets --include-windows-runtime-dlls=yes --assume-yes-for-downloads --output-filename=dist/toucan-plot-${{ steps.version.outputs.VERSION }}p.exe --windows-console-mode=disable --windows-icon-from-ico=src/toucan_plot/assets/ico/toucan-plot.ico --windows-uac-admin src/toucan_plot/main.py --product-name="TouCAN-Plot" --product-version=${{ steps.version.outputs.VERSION }} --file-description="A versatile PyQt6 and Matplotlib-based plotting tool for CSV and SMV data files." --copyright="Claudio Lima <claudiiolima@gmail.com> and contributors. Distributed under MIT license." --enable-plugin=pyside6

    - name: Build with Nuitka
      run: |
        .\.venv\Scripts\activate
        uv --no-progress run -- nuitka --mode=standalone --include-package=chardet --include-package=scienceplots --follow-imports --include-package-data=chardet --include-package-data=scienceplots --include-data-dir=src/toucan_plot/assets=assets --include-windows-runtime-dlls=yes --assume-yes-for-downloads --output-folder-name=TouCAN-Plot --windows-console-mode=disable --windows-icon-from-ico=src/toucan_plot/assets/ico/toucan-plot.ico src/toucan_plot/main.py --product-name="TouCAN-Plot" --product-version=${{ steps.version.outputs.VERSION }} --file-description="A versatile PyQt6 and Matplotlib-based plotting tool for CSV and SMV data files." --copyright="Claudio Lima <claudiiolima@gmail.com> and contributors. Distributed under MIT license." --enable-plugin=pyside6
        makensis /DVERSION="${{ steps.version.outputs.VERSION }}" ./.installer/toucan-plot.nsi
        move .installer/*.exe dist
